# VwaTek Apply - Google Cloud Build Pipeline
# Comprehensive CI/CD for automated deployments
# Triggers: Push to main branch or manual trigger

substitutions:
  _REGION: us-central1
  _BACKEND_SERVICE: vwatek-backend
  _FRONTEND_BUCKET: vwatek-apply-web
  _CLOUD_SQL_INSTANCE: vwatek-apply:us-central1:vwatekapply

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

steps:
  # ============================================
  # Stage 1: Build Backend
  # ============================================
  - id: 'build-backend'
    name: 'gradle:8.5-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x gradlew
        ./gradlew :backend:build -x test --no-daemon
        echo "✅ Backend build complete"

  # ============================================
  # Stage 2: Run Tests
  # ============================================
  - id: 'test-backend'
    name: 'gradle:8.5-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ./gradlew :backend:test --no-daemon || echo "⚠️ Some tests failed, continuing..."
    waitFor: ['build-backend']

  # ============================================
  # Stage 3: Build Backend Docker Image
  # ============================================
  - id: 'docker-build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'
    waitFor: ['build-backend']

  # ============================================
  # Stage 4: Push to Container Registry
  # ============================================
  - id: 'docker-push-sha'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA']
    waitFor: ['docker-build']

  - id: 'docker-push-latest'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest']
    waitFor: ['docker-build']

  # ============================================
  # Stage 5: Deploy Backend to Cloud Run
  # ============================================
  - id: 'deploy-backend'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ${_BACKEND_SERVICE} \
          --image=gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --add-cloudsql-instances=${_CLOUD_SQL_INSTANCE} \
          --set-env-vars="CLOUD_SQL_DATABASE=Vwatek_Apply,ENVIRONMENT=production" \
          --set-secrets="CLOUD_SQL_USER=db-username:latest,CLOUD_SQL_PASSWORD=db-password:latest,GEMINI_API_KEY=gemini-api-key:latest" \
          --min-instances=0 \
          --max-instances=10 \
          --memory=1Gi \
          --cpu=2 \
          --port=8080 \
          --timeout=300s
        echo "✅ Backend deployed to Cloud Run"
    waitFor: ['docker-push-sha']

  # ============================================
  # Stage 6: Verify Backend Health
  # ============================================
  - id: 'health-check'
    name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe ${_BACKEND_SERVICE} --region=${_REGION} --format='value(status.url)')
        echo "Backend URL: $BACKEND_URL"
        sleep 30
        response=$(curl -s -o /dev/null -w "%{http_code}" "$BACKEND_URL/health")
        if [ "$response" = "200" ]; then
          echo "✅ Backend health check passed"
        else
          echo "⚠️ Health check returned $response"
        fi
    waitFor: ['deploy-backend']

  # ============================================
  # Stage 7: Build Frontend
  # ============================================
  - id: 'build-frontend'
    name: 'gradle:8.5-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ./gradlew :webApp:jsBrowserDistribution --no-daemon
        echo "✅ Frontend build complete"
    waitFor: ['build-backend']

  # ============================================
  # Stage 8: Deploy Frontend to Cloud Storage
  # ============================================
  - id: 'deploy-frontend'
    name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Sync files
        gsutil -m rsync -r -d webApp/build/dist/js/productionExecutable/ gs://${_FRONTEND_BUCKET}/
        
        # Set cache headers for JS files
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://${_FRONTEND_BUCKET}/**/*.js
        
        # Set no-cache for HTML
        gsutil -m setmeta -h "Cache-Control:no-cache, no-store" gs://${_FRONTEND_BUCKET}/index.html
        
        echo "✅ Frontend deployed to Cloud Storage"
    waitFor: ['build-frontend', 'deploy-backend']

  # ============================================
  # Stage 9: Invalidate CDN Cache (if using Cloud CDN)
  # ============================================
  - id: 'invalidate-cache'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Invalidate CDN cache if load balancer exists
        gcloud compute url-maps invalidate-cdn-cache vwatek-lb --path="/*" 2>/dev/null || echo "No CDN to invalidate"
        echo "✅ Cache invalidation complete"
    waitFor: ['deploy-frontend']

images:
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest'

timeout: '1800s'

