# VwaTek Apply - Cloud Run Service Configuration
# Deploy with: gcloud run services replace cloudrun-service.yaml --region us-central1

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vwatek-backend
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        # Cloud SQL connection
        run.googleapis.com/cloudsql-instances: vwatek-apply:us-central1:vwatekapply
        # VPC Connector for private networking
        run.googleapis.com/vpc-access-connector: projects/vwatek-apply/locations/us-central1/connectors/vwatek-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        # Auto-scaling
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # CPU allocation
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: vwatek-cloudrun-sa@vwatek-apply.iam.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/vwatek-apply/vwatek-backend:latest
          ports:
            - containerPort: 8080
          env:
            # Database configuration using Secret Manager
            - name: CLOUD_SQL_INSTANCE
              value: "vwatek-apply:us-central1:vwatekapply"
            - name: CLOUD_SQL_HOST
              value: "34.134.196.247"
            - name: CLOUD_SQL_PORT
              value: "3306"
            - name: CLOUD_SQL_DATABASE
              value: "Vwatek_Apply"
            - name: CLOUD_SQL_USER
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: db-username
            - name: CLOUD_SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: db-password
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: gemini-api-key
            # Environment
            - name: ENVIRONMENT
              value: "production"
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 30
