name: VwaTekApply
options:
  bundleIdPrefix: com.vwatek
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  groupSortPosition: bottom

configs:
  Debug: debug
  Release: release

settingGroups:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: iosApp
        excludes:
          - "**/*.xcodeproj"
          - "**/*.xcworkspace"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vwatek.apply
        INFOPLIST_FILE: iosApp/Info.plist
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        OTHER_LDFLAGS: $(inherited) -ObjC
        FRAMEWORK_SEARCH_PATHS: $(inherited) "$(SRCROOT)/../shared/build/bin/iosSimulatorArm64/debugFramework"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          FRAMEWORK_SEARCH_PATHS: $(inherited) "$(SRCROOT)/../shared/build/bin/iosSimulatorArm64/debugFramework"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
          FRAMEWORK_SEARCH_PATHS: $(inherited) "$(SRCROOT)/../shared/build/bin/iosArm64/releaseFramework"
    preBuildScripts:
      - name: Build Shared Framework
        script: |
          cd "$SRCROOT/.."
          if [ "$CONFIGURATION" = "Debug" ]; then
            ./gradlew :shared:linkDebugFrameworkIosSimulatorArm64 --no-daemon
          else
            ./gradlew :shared:linkReleaseFrameworkIosArm64 --no-daemon
          fi
        basedOnDependencyAnalysis: false
    dependencies:
      - framework: ../shared/build/bin/iosSimulatorArm64/debugFramework/shared.framework
        embed: true
        link: true
      - sdk: libsqlite3.tbd

schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
